// Generated by npm run gen:herdr (packages/core). DO NOT EDIT.

// herdr 0.9.1; protocol 22; schema version 1; JSON Schema 2020-12.

export type Protocol = 22;

export type AgentInfo = {
  "agent"?: string | null;
  "agent_session"?: (AgentSessionInfo) | (null);
  "agent_status": AgentStatus;
  "cwd"?: string | null;
  "display_agent"?: string | null;
  "focused": boolean;
  "foreground_cwd"?: string | null;
  "interactive_ready"?: boolean;
  "launch_pending"?: boolean;
  "name"?: string | null;
  "pane_id": string;
  "revision": number;
  "screen_detection_skipped"?: boolean;
  "state_change_seq"?: number;
  "state_labels"?: {
    [key: string]: string;
  };
  "tab_id": string;
  "terminal_id": string;
  "terminal_title"?: string | null;
  "terminal_title_stripped"?: string | null;
  "title"?: string | null;
  "tokens"?: {
    [key: string]: string;
  };
  "workspace_id": string;
};

export type AgentManifestInfo = {
  "active_version"?: string | null;
  "agent": string;
  "cached_remote_version"?: string | null;
  "local_override_shadowing_remote": boolean;
  "remote_last_checked_unix"?: number | null;
  "remote_update_error"?: string | null;
  "remote_update_result"?: string | null;
  "source": string;
  "source_kind": string;
  "warning"?: string | null;
};

export type AgentPromptParams = {
  "target": string;
  "text": string;
  "wait"?: (AgentPromptWaitOptions) | (null);
};

export type AgentPromptWaitOptions = {
  "timeout_ms"?: number | null;
  "until"?: Array<AgentStatus>;
};

export type AgentReadParams = {
  "format"?: ReadFormat;
  "lines"?: number | null;
  "source": ReadSource;
  "strip_ansi"?: boolean;
  "target": string;
};

export type AgentRenameParams = {
  "name"?: string | null;
  "target": string;
};

export type AgentSendKeysParams = {
  "keys": Array<string>;
  "target": string;
};

export type AgentSessionInfo = {
  "agent": string;
  "kind": AgentSessionRefKind;
  "source": string;
  "value": string;
};

export type AgentSessionRefKind = "id" | "path";

export type AgentStartParams = {
  "args"?: Array<string>;
  "kind": string;
  "name": string;
  "pane_id": string;
  "timeout_ms"?: number | null;
};

export type AgentStatus = "idle" | "working" | "blocked" | "done" | "unknown";

export type AgentTarget = {
  "target": string;
};

export type AgentViewBuiltinField = "status" | "workspace_id" | "tab_id" | "pane_id" | "agent" | "seen" | "state_change_seq";

export type AgentViewBuiltinSortField = "workspace_order" | "tab_order" | "pane_order" | "attention" | "status" | "agent" | "seen" | "state_change_seq";

export type AgentViewClearParams = {
  "source"?: string | null;
};

export type AgentViewContext = "current_workspace_id" | "current_tab_id";

export type AgentViewField = (AgentViewBuiltinField) | ({
  "token": string;
});

export type AgentViewFilter = ({
  "filters": Array<AgentViewFilter>;
  "op": "all";
}) | ({
  "filters": Array<AgentViewFilter>;
  "op": "any";
}) | ({
  "filter": AgentViewFilter;
  "op": "not";
}) | ({
  "field": AgentViewField;
  "op": "eq";
  "value": AgentViewValue;
}) | ({
  "field": AgentViewField;
  "op": "in";
  "values": Array<AgentViewValue>;
}) | ({
  "field": AgentViewField;
  "op": "exists";
});

export type AgentViewSetParams = {
  "filter"?: (AgentViewFilter) | (null);
  "label"?: string | null;
  "sort"?: Array<AgentViewSort>;
  "source": string;
};

export type AgentViewSort = {
  "field": AgentViewSortField;
  "order"?: AgentViewSortOrder;
};

export type AgentViewSortField = (AgentViewBuiltinSortField) | ({
  "token": string;
});

export type AgentViewSortOrder = "asc" | "desc";

export type AgentViewValue = (string) | (boolean) | (number) | ({
  "context": AgentViewContext;
});

export type AgentWaitParams = {
  "target": string;
  "timeout_ms"?: number | null;
  "until"?: Array<AgentStatus>;
};

export type ClientShellSurfaceSetParams = {
  "active": boolean;
};

export type ClientWindowTitleReason = "set" | "cleared" | "no_foreground_client";

export type ClientWindowTitleSetParams = {
  "title": string;
};

export type CommandInvokeParams = {
  "command_id": string;
  "pane_id"?: string | null;
  "selection"?: (PaneSelectionReadParams) | (null);
  "tab_id"?: string | null;
  "workspace_id"?: string | null;
};

export type ConfigReloadStatus = "applied" | "partial" | "failed";

export type EmptyParams = Record<string, unknown>;

export type ErrorBody = {
  "code": string;
  "message": string;
};

export type EventData = ({
  "type": "workspace_created";
  "workspace": WorkspaceInfo;
}) | ({
  "type": "workspace_updated";
  "workspace": WorkspaceInfo;
}) | ({
  "type": "workspace_metadata_updated";
  "workspace": WorkspaceInfo;
}) | ({
  "type": "workspace_closed";
  "workspace"?: (WorkspaceInfo) | (null);
  "workspace_id": string;
}) | ({
  "label": string;
  "type": "workspace_renamed";
  "workspace_id": string;
}) | ({
  "insert_index": number;
  "type": "workspace_moved";
  "workspace_id": string;
  "workspaces": Array<WorkspaceInfo>;
}) | ({
  "before_workspace_id"?: string | null;
  "type": "workspace_reordered";
  "workspace_ids": Array<string>;
  "workspaces": Array<WorkspaceInfo>;
}) | ({
  "type": "workspace_focused";
  "workspace_id": string;
}) | ({
  "type": "worktree_created";
  "workspace": WorkspaceInfo;
  "worktree": WorktreeInfo;
}) | ({
  "already_open": boolean;
  "type": "worktree_opened";
  "workspace": WorkspaceInfo;
  "worktree": WorktreeInfo;
}) | ({
  "forced": boolean;
  "type": "worktree_removed";
  "workspace"?: (WorkspaceInfo) | (null);
  "workspace_id": string;
  "worktree": WorktreeInfo;
}) | ({
  "tab": TabInfo;
  "type": "tab_created";
}) | ({
  "tab_id": string;
  "type": "tab_closed";
  "workspace_id": string;
}) | ({
  "label": string;
  "tab_id": string;
  "type": "tab_renamed";
  "workspace_id": string;
}) | ({
  "insert_index": number;
  "tab_id": string;
  "tabs": Array<TabInfo>;
  "type": "tab_moved";
  "workspace_id": string;
}) | ({
  "tab_id": string;
  "type": "tab_focused";
  "workspace_id": string;
}) | ({
  "pane": PaneInfo;
  "type": "pane_created";
}) | ({
  "pane_id": string;
  "type": "pane_closed";
  "workspace_id": string;
}) | ({
  "pane": PaneInfo;
  "type": "pane_updated";
}) | ({
  "pane_id": string;
  "type": "pane_focused";
  "workspace_id": string;
}) | ({
  "closed_tab_id"?: string | null;
  "closed_workspace_id"?: string | null;
  "created_tab"?: (TabInfo) | (null);
  "created_workspace"?: (WorkspaceInfo) | (null);
  "pane": PaneInfo;
  "previous_pane_id": string;
  "previous_tab_id": string;
  "previous_workspace_id": string;
  "type": "pane_moved";
}) | ({
  "pane_id": string;
  "revision": number;
  "type": "pane_output_changed";
  "workspace_id": string;
}) | ({
  "pane_id": string;
  "type": "pane_exited";
  "workspace_id": string;
}) | ({
  "agent"?: string | null;
  "final_status"?: (AgentStatus) | (null);
  "pane_id": string;
  "released"?: boolean;
  "type": "pane_agent_detected";
  "workspace_id": string;
}) | ({
  "agent"?: string | null;
  "agent_status": AgentStatus;
  "display_agent"?: string | null;
  "pane_id": string;
  "state_labels"?: {
    [key: string]: string;
  };
  "title"?: string | null;
  "type": "pane_agent_status_changed";
  "workspace_id": string;
}) | ({
  "layout": PaneLayoutSnapshot;
  "type": "layout_updated";
});

export type EventEnvelope = {
  "data": EventData;
  "event": EventKind;
};

export type EventKind = "workspace_created" | "workspace_updated" | "workspace_metadata_updated" | "workspace_closed" | "workspace_renamed" | "workspace_moved" | "workspace_reordered" | "workspace_focused" | "worktree_created" | "worktree_opened" | "worktree_removed" | "tab_created" | "tab_closed" | "tab_renamed" | "tab_moved" | "tab_focused" | "pane_created" | "pane_closed" | "pane_updated" | "pane_focused" | "pane_moved" | "pane_output_changed" | "pane_exited" | "pane_agent_detected" | "pane_agent_status_changed" | "layout_updated";

export type EventMatch = ({
  "event": "workspace_created";
  "workspace_id"?: string | null;
}) | ({
  "event": "workspace_updated";
  "workspace_id": string;
}) | ({
  "event": "workspace_closed";
  "workspace_id": string;
}) | ({
  "event": "workspace_renamed";
  "label"?: string | null;
  "workspace_id": string;
}) | ({
  "event": "workspace_moved";
  "workspace_id": string;
}) | ({
  "event": "workspace_focused";
  "workspace_id": string;
}) | ({
  "event": "tab_created";
  "tab_id"?: string | null;
  "workspace_id"?: string | null;
}) | ({
  "event": "tab_closed";
  "tab_id": string;
}) | ({
  "event": "tab_renamed";
  "label"?: string | null;
  "tab_id": string;
}) | ({
  "event": "tab_moved";
  "tab_id": string;
}) | ({
  "event": "tab_focused";
  "tab_id": string;
}) | ({
  "event": "pane_created";
  "pane_id"?: string | null;
  "workspace_id"?: string | null;
}) | ({
  "event": "pane_closed";
  "pane_id": string;
}) | ({
  "event": "pane_focused";
  "pane_id": string;
}) | ({
  "event": "pane_moved";
  "pane_id": string;
}) | ({
  "event": "pane_output_changed";
  "min_revision"?: number | null;
  "pane_id": string;
}) | ({
  "event": "pane_exited";
  "pane_id": string;
}) | ({
  "agent"?: string | null;
  "event": "pane_agent_detected";
  "pane_id": string;
}) | ({
  "agent_status": AgentStatus;
  "event": "pane_agent_status_changed";
  "pane_id": string;
});

export type EventsSubscribeParams = {
  "subscriptions": Array<Subscription>;
};

export type EventsWaitParams = {
  "match_event": EventMatch;
  "timeout_ms"?: number | null;
};

export type InstalledPluginInfo = {
  "actions"?: Array<PluginManifestAction>;
  "build"?: Array<PluginManifestBuild>;
  "description"?: string | null;
  "enabled": boolean;
  "events"?: Array<PluginManifestEventHook>;
  "link_handlers"?: Array<PluginManifestLinkHandler>;
  "manifest_path": string;
  "min_herdr_version"?: string;
  "name": string;
  "panes"?: Array<PluginManifestPane>;
  "platforms"?: Array<PluginPlatform> | null;
  "plugin_id": string;
  "plugin_root": string;
  "source"?: PluginSourceInfo;
  "startup"?: Array<PluginManifestStartup>;
  "version": string;
  "warnings"?: Array<string>;
};

export type IntegrationInfo = {
  "available": boolean;
  "command": string;
  "label": string;
  "state": IntegrationState;
  "target": IntegrationTarget;
};

export type IntegrationInstallParams = {
  "target": IntegrationTarget;
};

export type IntegrationInstallResult = {
  "messages": Array<string>;
};

export type IntegrationState = "not_installed" | "current" | "outdated";

export type IntegrationTarget = "pi" | "omp" | "claude" | "codex" | "copilot" | "devin" | "droid" | "kimi" | "opencode" | "kilo" | "hermes" | "qodercli" | "qwen" | "cursor" | "mastracode" | "antigravity_cli" | "grok";

export type IntegrationUninstallParams = {
  "target": IntegrationTarget;
};

export type IntegrationUninstallResult = {
  "messages": Array<string>;
};

export type LayoutApplyParams = {
  "focus"?: boolean;
  "root": LayoutNode;
  "tab_id"?: string | null;
  "tab_label"?: string | null;
  "workspace_id"?: string | null;
};

export type LayoutDescription = {
  "focused_pane_id": string;
  "root": LayoutNode;
  "tab_id": string;
  "workspace_id": string;
  "zoomed": boolean;
};

export type LayoutExportParams = {
  "pane_id"?: string | null;
  "tab_id"?: string | null;
};

export type LayoutNode = ({
  "command"?: Array<string> | null;
  "cwd"?: string | null;
  "env"?: {
    [key: string]: string;
  };
  "label"?: string | null;
  "pane_id"?: string | null;
  "type": "pane";
}) | ({
  "direction": SplitDirection;
  "first": LayoutNode;
  "ratio": number;
  "second": LayoutNode;
  "type": "split";
});

export type LayoutSetSplitRatioParams = {
  "pane_id"?: string | null;
  "path": Array<boolean>;
  "ratio": number;
  "tab_id"?: string | null;
};

export type NotificationShowParams = {
  "body"?: string | null;
  "position"?: (ToastHerdrPosition) | (null);
  "sound"?: NotificationShowSound;
  "title": string;
};

export type NotificationShowReason = "shown" | "disabled" | "rate_limited" | "no_foreground_client" | "busy";

export type NotificationShowSound = "none" | "done" | "request";

export type OutputMatch = ({
  "type": "substring";
  "value": string;
}) | ({
  "type": "regex";
  "value": string;
});

export type PaneAgentState = "idle" | "working" | "blocked" | "unknown";

export type PaneAgentStatusChangedEvent = {
  "agent"?: string | null;
  "agent_status": AgentStatus;
  "display_agent"?: string | null;
  "pane_id": string;
  "state_labels"?: {
    [key: string]: string;
  };
  "title"?: string | null;
  "workspace_id": string;
};

export type PaneClearAgentAuthorityParams = {
  "pane_id": string;
  "seq"?: number | null;
  "source"?: string | null;
};

export type PaneCopyMotion = "line_end" | "first_non_blank" | "next_word_start" | "previous_word_start" | "next_word_end" | "next_big_word_start" | "previous_big_word_start" | "next_big_word_end" | "previous_paragraph" | "next_paragraph";

export type PaneCopyMotionParams = {
  "content_revision"?: number | null;
  "cursor": PaneTextPoint;
  "motion": PaneCopyMotion;
  "pane_id": string;
};

export type PaneCopySearchDirection = "forward" | "backward";

export type PaneCopySearchParams = {
  "content_revision": number;
  "cursor": PaneTextPoint;
  "direction": PaneCopySearchDirection;
  "pane_id": string;
  "previous"?: (PaneTextRange) | (null);
  "query": string;
};

export type PaneCurrentParams = {
  "caller_pane_id"?: string | null;
};

export type PaneDirection = "left" | "right" | "up" | "down";

export type PaneEdgesParams = {
  "pane_id"?: string | null;
};

export type PaneEdgesResult = {
  "down": boolean;
  "layout": PaneLayoutSnapshot;
  "left": boolean;
  "pane_id": string;
  "right": boolean;
  "up": boolean;
};

export type PaneFocusDirectionParams = {
  "direction": PaneDirection;
  "pane_id"?: string | null;
};

export type PaneFocusDirectionReason = "no_neighbor";

export type PaneFocusDirectionResult = {
  "changed": boolean;
  "focused_pane_id"?: string | null;
  "layout": PaneLayoutSnapshot;
  "reason"?: (PaneFocusDirectionReason) | (null);
  "source_pane_id": string;
};

export type PaneGraphicsClearParams = {
  "layer_id"?: string | null;
  "pane_id": string;
};

export type PaneGraphicsFormat = "png" | "rgb" | "rgba" | "bgra";

export type PaneGraphicsPlacementParams = {
  "grid_cols"?: number;
  "grid_rows"?: number;
  "viewport_col"?: number;
  "viewport_row"?: number;
};

export type PaneGraphicsSetParams = {
  "data_base64"?: string;
  "format": PaneGraphicsFormat;
  "image_height": number;
  "image_width": number;
  "layer_id"?: string | null;
  "pane_id": string;
  "placement"?: PaneGraphicsPlacementParams;
  "z_index"?: number;
};

export type PaneInfo = {
  "agent"?: string | null;
  "agent_session"?: (AgentSessionInfo) | (null);
  "agent_status": AgentStatus;
  "cwd"?: string | null;
  "display_agent"?: string | null;
  "focused": boolean;
  "foreground_cwd"?: string | null;
  "label"?: string | null;
  "pane_id": string;
  "revision": number;
  "scroll"?: (PaneScrollInfo) | (null);
  "state_labels"?: {
    [key: string]: string;
  };
  "tab_id": string;
  "terminal_id": string;
  "terminal_title"?: string | null;
  "terminal_title_stripped"?: string | null;
  "title"?: string | null;
  "tokens"?: {
    [key: string]: string;
  };
  "workspace_id": string;
};

export type PaneInputSetParams = {
  "pane_id": string;
  "right_click": PaneRightClickTarget;
};

export type PaneLayoutPane = {
  "focused": boolean;
  "pane_id": string;
  "rect": PaneLayoutRect;
};

export type PaneLayoutParams = {
  "pane_id"?: string | null;
};

export type PaneLayoutRect = {
  "height": number;
  "width": number;
  "x": number;
  "y": number;
};

export type PaneLayoutSnapshot = {
  "area": PaneLayoutRect;
  "focused_pane_id": string;
  "panes": Array<PaneLayoutPane>;
  "splits": Array<PaneLayoutSplit>;
  "tab_id": string;
  "workspace_id": string;
  "zoomed": boolean;
};

export type PaneLayoutSplit = {
  "direction": SplitDirection;
  "id": string;
  "ratio": number;
  "rect": PaneLayoutRect;
};

export type PaneLinkActivateParams = {
  "col": number;
  "content_revision"?: number | null;
  "offset_from_bottom"?: number | null;
  "pane_id": string;
  "viewport_row": number;
};

export type PaneLinkRegion = {
  "end_col": number;
  "row": number;
  "start_col": number;
};

export type PaneListParams = {
  "workspace_id"?: string | null;
};

export type PaneMoveDestination = ({
  "ratio"?: number | null;
  "split": SplitDirection;
  "tab_id": string;
  "target_pane_id"?: string | null;
  "type": "tab";
}) | ({
  "label"?: string | null;
  "type": "new_tab";
  "workspace_id"?: string | null;
}) | ({
  "label"?: string | null;
  "tab_label"?: string | null;
  "type": "new_workspace";
});

export type PaneMoveParams = {
  "destination": PaneMoveDestination;
  "focus"?: boolean;
  "pane_id": string;
};

export type PaneMoveReason = "same_tab" | "zoomed_tab";

export type PaneMoveResult = {
  "changed": boolean;
  "closed_tab_id"?: string | null;
  "closed_workspace_id"?: string | null;
  "created_tab"?: (TabInfo) | (null);
  "created_workspace"?: (WorkspaceInfo) | (null);
  "focused_pane_id": string;
  "pane": PaneInfo;
  "previous_pane_id": string;
  "previous_tab_id": string;
  "previous_workspace_id": string;
  "reason"?: (PaneMoveReason) | (null);
  "source_layout"?: (PaneLayoutSnapshot) | (null);
  "target_layout": PaneLayoutSnapshot;
};

export type PaneNeighborParams = {
  "direction": PaneDirection;
  "pane_id"?: string | null;
};

export type PaneNeighborResult = {
  "direction": PaneDirection;
  "layout": PaneLayoutSnapshot;
  "neighbor_pane_id"?: string | null;
  "pane_id": string;
};

export type PaneOutputMatchedEvent = {
  "matched_line": string;
  "pane_id": string;
  "read": PaneReadResult;
};

export type PaneProcessInfo = {
  "foreground_process_group_id"?: number | null;
  "foreground_processes"?: Array<PaneProcessInfoProcess>;
  "pane_id": string;
  "shell_pid"?: number | null;
  "tty"?: string | null;
};

export type PaneProcessInfoParams = {
  "pane_id"?: string | null;
};

export type PaneProcessInfoProcess = {
  "argv"?: Array<string> | null;
  "argv0"?: string | null;
  "cmdline"?: string | null;
  "cwd"?: string | null;
  "name": string;
  "pid": number;
};

export type PaneReadParams = {
  "format"?: ReadFormat;
  "lines"?: number | null;
  "pane_id": string;
  "source": ReadSource;
  "strip_ansi"?: boolean;
};

export type PaneReadResult = {
  "format": ReadFormat;
  "pane_id": string;
  "revision": number;
  "source": ReadSource;
  "tab_id": string;
  "text": string;
  "truncated": boolean;
  "workspace_id": string;
};

export type PaneReleaseAgentParams = {
  "agent": string;
  "pane_id": string;
  "seq"?: number | null;
  "source": string;
};

export type PaneRenameParams = {
  "label"?: string | null;
  "pane_id": string;
};

export type PaneReportAgentParams = {
  "agent": string;
  "agent_session_id"?: string | null;
  "agent_session_path"?: string | null;
  "message"?: string | null;
  "pane_id": string;
  "seq"?: number | null;
  "source": string;
  "state": PaneAgentState;
};

export type PaneReportAgentSessionParams = {
  "agent": string;
  "agent_session_id"?: string | null;
  "agent_session_path"?: string | null;
  "pane_id": string;
  "seq"?: number | null;
  "session_start_source"?: string | null;
  "source": string;
};

export type PaneReportMetadataParams = {
  "agent"?: string | null;
  "applies_to_source"?: string | null;
  "clear_display_agent"?: boolean;
  "clear_state_labels"?: boolean;
  "clear_title"?: boolean;
  "display_agent"?: string | null;
  "pane_id": string;
  "seq"?: number | null;
  "source": string;
  "state_labels"?: {
    [key: string]: string;
  };
  "title"?: string | null;
  "tokens"?: {
    [key: string]: string | null;
  };
  "ttl_ms"?: number | null;
};

export type PaneResizeParams = {
  "amount"?: number | null;
  "direction": PaneDirection;
  "pane_id"?: string | null;
};

export type PaneResizeReason = "unchanged";

export type PaneResizeResult = {
  "changed": boolean;
  "focused_pane_id": string;
  "layout": PaneLayoutSnapshot;
  "pane_id": string;
  "reason"?: (PaneResizeReason) | (null);
};

export type PaneRightClickTarget = "herdr" | "pane";

export type PaneScrollChangedEvent = {
  "pane_id": string;
  "scroll": PaneScrollInfo;
  "workspace_id": string;
};

export type PaneScrollInfo = {
  "max_offset_from_bottom": number;
  "offset_from_bottom": number;
  "viewport_rows": number;
};

export type PaneScrollParams = {
  "offset_from_bottom": number;
  "pane_id": string;
};

export type PaneSelectionReadParams = {
  "anchor": PaneTextPoint;
  "content_revision"?: number | null;
  "cursor": PaneTextPoint;
  "pane_id": string;
};

export type PaneSendInputParams = {
  "keys"?: Array<string>;
  "pane_id": string;
  "text"?: string;
};

export type PaneSendKeysParams = {
  "keys": Array<string>;
  "pane_id": string;
};

export type PaneSendTextParams = {
  "pane_id": string;
  "text": string;
};

export type PaneSplitParams = {
  "cwd"?: string | null;
  "direction": SplitDirection;
  "env"?: {
    [key: string]: string;
  };
  "focus"?: boolean;
  "ratio"?: number | null;
  "right_click"?: PaneRightClickTarget;
  "target_pane_id"?: string | null;
  "workspace_id"?: string | null;
};

export type PaneSwapParams = {
  "direction"?: (PaneDirection) | (null);
  "pane_id"?: string | null;
  "source_pane_id"?: string | null;
  "target_pane_id"?: string | null;
};

export type PaneSwapReason = "no_neighbor" | "same_pane" | "not_found" | "cross_tab";

export type PaneSwapResult = {
  "changed": boolean;
  "focused_pane_id": string;
  "layout": PaneLayoutSnapshot;
  "reason"?: (PaneSwapReason) | (null);
  "source_pane_id": string;
  "target_pane_id"?: string | null;
};

export type PaneTarget = {
  "pane_id": string;
};

export type PaneTextPoint = {
  "col": number;
  "row": number;
};

export type PaneTextRange = {
  "end": PaneTextPoint;
  "start": PaneTextPoint;
};

export type PaneWaitForOutputParams = {
  "lines"?: number | null;
  "match": OutputMatch;
  "pane_id": string;
  "source": ReadSource;
  "strip_ansi"?: boolean;
  "timeout_ms"?: number | null;
};

export type PaneZoomMode = "toggle" | "on" | "off";

export type PaneZoomParams = {
  "mode"?: PaneZoomMode;
  "pane_id"?: string | null;
};

export type PaneZoomReason = "single_pane" | "already_zoomed" | "already_unzoomed";

export type PaneZoomResult = {
  "changed": boolean;
  "focus_changed": boolean;
  "focused_pane_id": string;
  "layout": PaneLayoutSnapshot;
  "pane_id": string;
  "reason"?: (PaneZoomReason) | (null);
  "zoom_changed": boolean;
  "zoomed": boolean;
};

export type PingParams = Record<string, unknown>;

export type PluginActionContext = "global" | "workspace" | "tab" | "pane" | "selection";

export type PluginActionInfo = {
  "action_id": string;
  "command": Array<string>;
  "contexts"?: Array<PluginActionContext>;
  "description"?: string | null;
  "platforms"?: Array<PluginPlatform> | null;
  "plugin_id": string;
  "title": string;
};

export type PluginActionInvokeParams = {
  "action_id": string;
  "context"?: (PluginInvocationContext) | (null);
  "plugin_id"?: string | null;
};

export type PluginActionListParams = {
  "plugin_id"?: string | null;
};

export type PluginCommandLogInfo = {
  "action_id"?: string | null;
  "command": Array<string>;
  "error"?: string | null;
  "event"?: string | null;
  "exit_code"?: number | null;
  "finished_unix_ms"?: number | null;
  "log_id": string;
  "plugin_id": string;
  "started_unix_ms": number;
  "status": PluginCommandStatus;
  "stderr"?: string | null;
  "stdout"?: string | null;
};

export type PluginCommandStatus = "running" | "succeeded" | "failed";

export type PluginInvocationContext = {
  "clicked_url"?: string | null;
  "correlation_id"?: string | null;
  "focused_pane_agent"?: string | null;
  "focused_pane_cwd"?: string | null;
  "focused_pane_id"?: string | null;
  "focused_pane_status"?: (AgentStatus) | (null);
  "invocation_source"?: string | null;
  "link_handler_id"?: string | null;
  "selected_text"?: string | null;
  "tab_id"?: string | null;
  "tab_label"?: string | null;
  "workspace_cwd"?: string | null;
  "workspace_id"?: string | null;
  "workspace_label"?: string | null;
  "worktree"?: (WorkspaceWorktreeInfo) | (null);
};

export type PluginLinkParams = {
  "enabled"?: boolean;
  "path": string;
  "source"?: (PluginSourceInfo) | (null);
};

export type PluginListParams = {
  "plugin_id"?: string | null;
};

export type PluginLogListParams = {
  "limit"?: number | null;
  "plugin_id"?: string | null;
};

export type PluginManifestAction = {
  "command": Array<string>;
  "contexts"?: Array<PluginActionContext>;
  "description"?: string | null;
  "id": string;
  "platforms"?: Array<PluginPlatform> | null;
  "title": string;
};

export type PluginManifestBuild = {
  "command": Array<string>;
  "platforms"?: Array<PluginPlatform> | null;
};

export type PluginManifestEventHook = {
  "command": Array<string>;
  "on": string;
  "platforms"?: Array<PluginPlatform> | null;
};

export type PluginManifestLinkHandler = {
  "action": string;
  "id": string;
  "pattern": string;
  "platforms"?: Array<PluginPlatform> | null;
  "title": string;
};

export type PluginManifestPane = {
  "command": Array<string>;
  "description"?: string | null;
  "height"?: (PopupSize) | (null);
  "id": string;
  "placement"?: PluginPanePlacement;
  "platforms"?: Array<PluginPlatform> | null;
  "title": string;
  "width"?: (PopupSize) | (null);
};

export type PluginManifestStartup = {
  "command": Array<string>;
  "platforms"?: Array<PluginPlatform> | null;
};

export type PluginPaneCloseParams = {
  "pane_id": string;
};

export type PluginPaneFocusParams = {
  "pane_id": string;
};

export type PluginPaneInfo = {
  "entrypoint": string;
  "pane": PaneInfo;
  "plugin_id": string;
};

export type PluginPaneOpenParams = {
  "cwd"?: string | null;
  "direction"?: (SplitDirection) | (null);
  "entrypoint": string;
  "env"?: {
    [key: string]: string;
  };
  "focus"?: boolean;
  "height"?: (PopupSize) | (null);
  "placement"?: (PluginPanePlacement) | (null);
  "plugin_id": string;
  "target_pane_id"?: string | null;
  "width"?: (PopupSize) | (null);
  "workspace_id"?: string | null;
};

export type PluginPanePlacement = "overlay" | "popup" | "split" | "tab" | "zoomed";

export type PluginPlatform = "linux" | "macos" | "windows";

export type PluginSetEnabledParams = {
  "plugin_id": string;
};

export type PluginSourceInfo = {
  "installed_unix_ms"?: number | null;
  "kind"?: PluginSourceKind;
  "managed_path"?: string | null;
  "owner"?: string | null;
  "repo"?: string | null;
  "requested_ref"?: string | null;
  "resolved_commit"?: string | null;
  "subdir"?: string | null;
};

export type PluginSourceKind = "local" | "github";

export type PluginUnlinkParams = {
  "plugin_id": string;
};

export type PopupSize = (number) | (string);

export type ProductAnnouncementDismissParams = {
  "id": string;
  "version": string;
};

export type ReadFormat = "text" | "ansi";

export type ReadSource = "visible" | "recent" | "recent_unwrapped" | "detection";

export type ReleaseNotesDismissParams = {
  "version": string;
};

export type ResponseResult = ({
  "capabilities"?: (ServerCapabilities) | (null);
  "protocol": number;
  "type": "pong";
  "version": string;
}) | ({
  "snapshot": SessionSnapshot;
  "type": "session_snapshot";
}) | ({
  "type": "workspace_info";
  "workspace": WorkspaceInfo;
}) | ({
  "root_pane": PaneInfo;
  "tab": TabInfo;
  "type": "workspace_created";
  "workspace": WorkspaceInfo;
}) | ({
  "type": "workspace_list";
  "workspaces": Array<WorkspaceInfo>;
}) | ({
  "source": WorktreeSourceInfo;
  "type": "worktree_list";
  "worktrees": Array<WorktreeInfo>;
}) | ({
  "root_pane": PaneInfo;
  "tab": TabInfo;
  "type": "worktree_created";
  "workspace": WorkspaceInfo;
  "worktree": WorktreeInfo;
}) | ({
  "already_open": boolean;
  "root_pane": PaneInfo;
  "tab": TabInfo;
  "type": "worktree_opened";
  "workspace": WorkspaceInfo;
  "worktree": WorktreeInfo;
}) | ({
  "forced": boolean;
  "path": string;
  "type": "worktree_removed";
  "workspace_id": string;
}) | ({
  "tab": TabInfo;
  "type": "tab_info";
}) | ({
  "root_pane": PaneInfo;
  "tab": TabInfo;
  "type": "tab_created";
}) | ({
  "tabs": Array<TabInfo>;
  "type": "tab_list";
}) | ({
  "agent": AgentInfo;
  "type": "agent_info";
}) | ({
  "agent": AgentInfo;
  "argv": Array<string>;
  "type": "agent_started";
}) | ({
  "agent": AgentInfo;
  "type": "agent_prompted";
}) | ({
  "agents": Array<AgentInfo>;
  "type": "agent_list";
}) | ({
  "active": boolean;
  "label"?: string | null;
  "source"?: string | null;
  "type": "agent_view";
}) | ({
  "pane": PaneInfo;
  "type": "pane_info";
}) | ({
  "panes": Array<PaneInfo>;
  "type": "pane_list";
}) | ({
  "pane": PaneInfo;
  "type": "pane_current";
}) | ({
  "swap": PaneSwapResult;
  "type": "pane_swap";
}) | ({
  "move_result": PaneMoveResult;
  "type": "pane_move";
}) | ({
  "type": "pane_zoom";
  "zoom": PaneZoomResult;
}) | ({
  "layout": PaneLayoutSnapshot;
  "type": "pane_layout";
}) | ({
  "process_info": PaneProcessInfo;
  "type": "pane_process_info";
}) | ({
  "layout": LayoutDescription;
  "type": "layout_export";
}) | ({
  "layout": LayoutDescription;
  "type": "layout_apply";
}) | ({
  "layout": LayoutDescription;
  "type": "layout_split_ratio_set";
}) | ({
  "neighbor": PaneNeighborResult;
  "type": "pane_neighbor";
}) | ({
  "edges": PaneEdgesResult;
  "type": "pane_edges";
}) | ({
  "focus": PaneFocusDirectionResult;
  "type": "pane_focus_direction";
}) | ({
  "resize": PaneResizeResult;
  "type": "pane_resize";
}) | ({
  "read": PaneReadResult;
  "type": "pane_read";
}) | ({
  "pane_id": string;
  "text": string;
  "type": "pane_selection";
}) | ({
  "content_revision": number;
  "cursor": PaneTextPoint;
  "pane_id": string;
  "type": "pane_copy_motion";
}) | ({
  "content_revision": number;
  "current"?: number | null;
  "current_global"?: number | null;
  "matches": Array<PaneTextRange>;
  "pane_id": string;
  "total": number;
  "type": "pane_copy_search";
}) | ({
  "revision": number;
  "sequence": number;
  "type": "pane_graphics_frame_ack";
}) | ({
  "cell_height_px": number;
  "cell_width_px": number;
  "file_frame_damage"?: boolean;
  "file_frame_direct_max_bytes"?: number | null;
  "file_frame_directory"?: string | null;
  "file_frame_formats"?: Array<string>;
  "file_frame_max_bytes"?: number | null;
  "file_frame_transport"?: string | null;
  "max_layers_per_pane"?: number;
  "pane_visible": boolean;
  "pixel_mouse"?: boolean;
  "type": "pane_graphics_info";
}) | ({
  "explain": unknown;
  "type": "agent_explain";
}) | ({
  "type": "subscription_started";
}) | ({
  "event": EventEnvelope;
  "type": "wait_matched";
}) | ({
  "matched_line"?: string | null;
  "pane_id": string;
  "read": PaneReadResult;
  "revision": number;
  "type": "output_matched";
}) | ({
  "reason": NotificationShowReason;
  "shown": boolean;
  "type": "notification_show";
}) | ({
  "changed": boolean;
  "reason": ClientWindowTitleReason;
  "type": "client_window_title";
}) | ({
  "integrations": Array<IntegrationInfo>;
  "type": "integration_list";
}) | ({
  "details": IntegrationInstallResult;
  "target": IntegrationTarget;
  "type": "integration_install";
}) | ({
  "details": IntegrationUninstallResult;
  "target": IntegrationTarget;
  "type": "integration_uninstall";
}) | ({
  "manifests": Array<AgentManifestInfo>;
  "type": "agent_manifest_reload";
}) | ({
  "last_check_unix"?: number | null;
  "last_result"?: string | null;
  "manifests": Array<AgentManifestInfo>;
  "type": "agent_manifest_status";
}) | ({
  "plugin": InstalledPluginInfo;
  "type": "plugin_linked";
}) | ({
  "plugins": Array<InstalledPluginInfo>;
  "type": "plugin_list";
}) | ({
  "plugin_id": string;
  "removed": boolean;
  "type": "plugin_unlinked";
}) | ({
  "plugin": InstalledPluginInfo;
  "type": "plugin_enabled";
}) | ({
  "plugin": InstalledPluginInfo;
  "type": "plugin_disabled";
}) | ({
  "actions": Array<PluginActionInfo>;
  "type": "plugin_action_list";
}) | ({
  "action": PluginActionInfo;
  "context": PluginInvocationContext;
  "log": PluginCommandLogInfo;
  "type": "plugin_action_invoked";
}) | ({
  "regions": Array<PaneLinkRegion>;
  "type": "pane_link_resolved";
}) | ({
  "handled": boolean;
  "type": "pane_link_activated";
  "url"?: string | null;
}) | ({
  "logs": Array<PluginCommandLogInfo>;
  "type": "plugin_log_list";
}) | ({
  "plugin_pane": PluginPaneInfo;
  "type": "plugin_pane_opened";
}) | ({
  "plugin_pane": PluginPaneInfo;
  "type": "plugin_pane_focused";
}) | ({
  "pane_id": string;
  "type": "plugin_pane_closed";
}) | ({
  "diagnostics": Array<string>;
  "status": ConfigReloadStatus;
  "type": "config_reload";
}) | ({
  "active": boolean;
  "projection_revision": number;
  "type": "client_shell_surface_set";
}) | ({
  "type": "ok";
});

export type ServerCapabilities = {
  "detached_server_daemon"?: boolean;
  "endpoint_protocol_generation"?: number | null;
  "health_check"?: boolean;
  "live_handoff": boolean;
  "surface_interest"?: boolean;
};

export type ServerLiveHandoffParams = {
  "expected_protocol"?: number | null;
  "expected_version"?: string | null;
  "import_exe"?: string | null;
};

export type SessionSnapshot = {
  "agents": Array<AgentInfo>;
  "focused_pane_id"?: string | null;
  "focused_tab_id"?: string | null;
  "focused_workspace_id"?: string | null;
  "layouts": Array<PaneLayoutSnapshot>;
  "panes": Array<PaneInfo>;
  "protocol": number;
  "tabs": Array<TabInfo>;
  "version": string;
  "workspaces": Array<WorkspaceInfo>;
};

export type SplitDirection = "right" | "down";

export type Subscription = ({
  "type": "workspace.created";
}) | ({
  "type": "workspace.updated";
}) | ({
  "type": "workspace.metadata_updated";
}) | ({
  "type": "workspace.renamed";
}) | ({
  "type": "workspace.moved";
}) | ({
  "type": "workspace.reordered";
}) | ({
  "type": "workspace.closed";
}) | ({
  "type": "workspace.focused";
}) | ({
  "type": "worktree.created";
}) | ({
  "type": "worktree.opened";
}) | ({
  "type": "worktree.removed";
}) | ({
  "type": "tab.created";
}) | ({
  "type": "tab.closed";
}) | ({
  "type": "tab.focused";
}) | ({
  "type": "tab.renamed";
}) | ({
  "type": "tab.moved";
}) | ({
  "type": "pane.created";
}) | ({
  "type": "pane.closed";
}) | ({
  "type": "pane.updated";
}) | ({
  "type": "pane.focused";
}) | ({
  "type": "pane.moved";
}) | ({
  "type": "pane.exited";
}) | ({
  "type": "pane.agent_detected";
}) | ({
  "lines"?: number | null;
  "match": OutputMatch;
  "pane_id": string;
  "source": ReadSource;
  "strip_ansi"?: boolean;
  "type": "pane.output_matched";
}) | ({
  "agent_status"?: (AgentStatus) | (null);
  "pane_id": string;
  "type": "pane.agent_status_changed";
}) | ({
  "pane_id": string;
  "type": "pane.scroll_changed";
}) | ({
  "type": "layout.updated";
});

export type SubscriptionEventData = (PaneOutputMatchedEvent) | (PaneAgentStatusChangedEvent) | (PaneScrollChangedEvent);

export type SubscriptionEventKind = "pane.output_matched" | "pane.agent_status_changed" | "pane.scroll_changed";

export type TabCreateParams = {
  "cwd"?: string | null;
  "env"?: {
    [key: string]: string;
  };
  "focus"?: boolean;
  "label"?: string | null;
  "workspace_id"?: string | null;
};

export type TabInfo = {
  "agent_status": AgentStatus;
  "focused": boolean;
  "label": string;
  "number": number;
  "pane_count": number;
  "tab_id": string;
  "workspace_id": string;
};

export type TabListParams = {
  "workspace_id"?: string | null;
};

export type TabMoveParams = {
  "insert_index": number;
  "tab_id": string;
};

export type TabRenameParams = {
  "label": string;
  "tab_id": string;
};

export type TabTarget = {
  "tab_id": string;
};

export type ToastHerdrPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right";

export type WorkspaceCloseParams = {
  "close_group"?: boolean;
  "workspace_id": string;
};

export type WorkspaceCreateParams = {
  "cwd"?: string | null;
  "env"?: {
    [key: string]: string;
  };
  "focus"?: boolean;
  "label"?: string | null;
  "source_workspace_id"?: string | null;
};

export type WorkspaceInfo = {
  "active_tab_id": string;
  "agent_status": AgentStatus;
  "focused": boolean;
  "label": string;
  "number": number;
  "pane_count": number;
  "tab_count": number;
  "tokens"?: {
    [key: string]: string;
  };
  "workspace_id": string;
  "worktree"?: (WorkspaceWorktreeInfo) | (null);
};

export type WorkspaceMoveBlockParams = {
  "before_workspace_id"?: string | null;
  "workspace_ids": Array<string>;
};

export type WorkspaceMoveParams = {
  "insert_index": number;
  "workspace_id": string;
};

export type WorkspaceRenameParams = {
  "label": string;
  "workspace_id": string;
};

export type WorkspaceReportMetadataParams = {
  "seq"?: number | null;
  "source": string;
  "tokens": {
    [key: string]: string | null;
  };
  "ttl_ms"?: number | null;
  "workspace_id": string;
};

export type WorkspaceTarget = {
  "workspace_id": string;
};

export type WorkspaceWorktreeInfo = {
  "checkout_path": string;
  "is_linked_worktree": boolean;
  "repo_key": string;
  "repo_name": string;
  "repo_root": string;
};

export type WorktreeCreateParams = {
  "base"?: string | null;
  "branch"?: string | null;
  "cwd"?: string | null;
  "focus"?: boolean;
  "label"?: string | null;
  "path"?: string | null;
  "trust_repository"?: boolean;
  "workspace_id"?: string | null;
};

export type WorktreeInfo = {
  "branch"?: string | null;
  "is_bare": boolean;
  "is_detached": boolean;
  "is_linked_worktree": boolean;
  "is_prunable": boolean;
  "label": string;
  "open_workspace_id"?: string | null;
  "path": string;
};

export type WorktreeListParams = {
  "cwd"?: string | null;
  "trust_repository"?: boolean;
  "workspace_id"?: string | null;
};

export type WorktreeOpenParams = {
  "branch"?: string | null;
  "cwd"?: string | null;
  "focus"?: boolean;
  "label"?: string | null;
  "path"?: string | null;
  "trust_repository"?: boolean;
  "workspace_id"?: string | null;
};

export type WorktreeRemoveParams = {
  "force"?: boolean;
  "trust_repository"?: boolean;
  "workspace_id": string;
};

export type WorktreeSourceInfo = {
  "repo_key": string;
  "repo_name": string;
  "repo_root": string;
  "source_checkout_path": string;
  "source_workspace_id"?: string | null;
};

export type ErrorResponse = {
  "error": ErrorBody;
  "id": string;
};

export type Request = ({
  "id": string;
}) & (({
  "method": "ping";
  "params": PingParams;
}) | ({
  "method": "server.stop";
  "params": EmptyParams;
}) | ({
  "method": "server.live_handoff";
  "params": ServerLiveHandoffParams;
}) | ({
  "method": "server.reload_config";
  "params": EmptyParams;
}) | ({
  "method": "server.agent_manifests";
  "params": EmptyParams;
}) | ({
  "method": "server.reload_agent_manifests";
  "params": EmptyParams;
}) | ({
  "method": "notification.show";
  "params": NotificationShowParams;
}) | ({
  "method": "product_announcement.dismiss";
  "params": ProductAnnouncementDismissParams;
}) | ({
  "method": "release_notes.dismiss";
  "params": ReleaseNotesDismissParams;
}) | ({
  "method": "command.invoke";
  "params": CommandInvokeParams;
}) | ({
  "method": "client.window_title.set";
  "params": ClientWindowTitleSetParams;
}) | ({
  "method": "client.window_title.clear";
  "params": EmptyParams;
}) | ({
  "method": "client_shell.surface.set";
  "params": ClientShellSurfaceSetParams;
}) | ({
  "method": "session.snapshot";
  "params": EmptyParams;
}) | ({
  "method": "workspace.create";
  "params": WorkspaceCreateParams;
}) | ({
  "method": "workspace.list";
  "params": EmptyParams;
}) | ({
  "method": "workspace.get";
  "params": WorkspaceTarget;
}) | ({
  "method": "workspace.focus";
  "params": WorkspaceTarget;
}) | ({
  "method": "workspace.rename";
  "params": WorkspaceRenameParams;
}) | ({
  "method": "workspace.move";
  "params": WorkspaceMoveParams;
}) | ({
  "method": "workspace.move_block";
  "params": WorkspaceMoveBlockParams;
}) | ({
  "method": "workspace.report_metadata";
  "params": WorkspaceReportMetadataParams;
}) | ({
  "method": "workspace.close";
  "params": WorkspaceCloseParams;
}) | ({
  "method": "worktree.list";
  "params": WorktreeListParams;
}) | ({
  "method": "worktree.create";
  "params": WorktreeCreateParams;
}) | ({
  "method": "worktree.open";
  "params": WorktreeOpenParams;
}) | ({
  "method": "worktree.remove";
  "params": WorktreeRemoveParams;
}) | ({
  "method": "tab.create";
  "params": TabCreateParams;
}) | ({
  "method": "tab.list";
  "params": TabListParams;
}) | ({
  "method": "tab.get";
  "params": TabTarget;
}) | ({
  "method": "tab.focus";
  "params": TabTarget;
}) | ({
  "method": "tab.rename";
  "params": TabRenameParams;
}) | ({
  "method": "tab.move";
  "params": TabMoveParams;
}) | ({
  "method": "tab.close";
  "params": TabTarget;
}) | ({
  "method": "agent.list";
  "params": EmptyParams;
}) | ({
  "method": "agent.get";
  "params": AgentTarget;
}) | ({
  "method": "agent.read";
  "params": AgentReadParams;
}) | ({
  "method": "agent.explain";
  "params": AgentTarget;
}) | ({
  "method": "agent.send_keys";
  "params": AgentSendKeysParams;
}) | ({
  "method": "agent.rename";
  "params": AgentRenameParams;
}) | ({
  "method": "agent.view.set";
  "params": AgentViewSetParams;
}) | ({
  "method": "agent.view.clear";
  "params": AgentViewClearParams;
}) | ({
  "method": "agent.focus";
  "params": AgentTarget;
}) | ({
  "method": "agent.start";
  "params": AgentStartParams;
}) | ({
  "method": "agent.prompt";
  "params": AgentPromptParams;
}) | ({
  "method": "agent.wait";
  "params": AgentWaitParams;
}) | ({
  "method": "pane.split";
  "params": PaneSplitParams;
}) | ({
  "method": "pane.swap";
  "params": PaneSwapParams;
}) | ({
  "method": "pane.move";
  "params": PaneMoveParams;
}) | ({
  "method": "pane.zoom";
  "params": PaneZoomParams;
}) | ({
  "method": "pane.layout";
  "params": PaneLayoutParams;
}) | ({
  "method": "pane.process_info";
  "params": PaneProcessInfoParams;
}) | ({
  "method": "layout.export";
  "params": LayoutExportParams;
}) | ({
  "method": "layout.apply";
  "params": LayoutApplyParams;
}) | ({
  "method": "layout.set_split_ratio";
  "params": LayoutSetSplitRatioParams;
}) | ({
  "method": "pane.neighbor";
  "params": PaneNeighborParams;
}) | ({
  "method": "pane.edges";
  "params": PaneEdgesParams;
}) | ({
  "method": "pane.focus_direction";
  "params": PaneFocusDirectionParams;
}) | ({
  "method": "pane.resize";
  "params": PaneResizeParams;
}) | ({
  "method": "pane.scroll";
  "params": PaneScrollParams;
}) | ({
  "method": "pane.edit_scrollback";
  "params": PaneTarget;
}) | ({
  "method": "pane.selection.read";
  "params": PaneSelectionReadParams;
}) | ({
  "method": "pane.copy_motion";
  "params": PaneCopyMotionParams;
}) | ({
  "method": "pane.copy_search";
  "params": PaneCopySearchParams;
}) | ({
  "method": "pane.list";
  "params": PaneListParams;
}) | ({
  "method": "pane.current";
  "params": PaneCurrentParams;
}) | ({
  "method": "pane.get";
  "params": PaneTarget;
}) | ({
  "method": "pane.focus";
  "params": PaneTarget;
}) | ({
  "method": "pane.input.set";
  "params": PaneInputSetParams;
}) | ({
  "method": "pane.link.activate";
  "params": PaneLinkActivateParams;
}) | ({
  "method": "pane.link.resolve";
  "params": PaneLinkActivateParams;
}) | ({
  "method": "pane.rename";
  "params": PaneRenameParams;
}) | ({
  "method": "pane.send_text";
  "params": PaneSendTextParams;
}) | ({
  "method": "pane.send_keys";
  "params": PaneSendKeysParams;
}) | ({
  "method": "pane.send_input";
  "params": PaneSendInputParams;
}) | ({
  "method": "pane.read";
  "params": PaneReadParams;
}) | ({
  "method": "pane.graphics.set";
  "params": PaneGraphicsSetParams;
}) | ({
  "method": "pane.graphics.clear";
  "params": PaneGraphicsClearParams;
}) | ({
  "method": "pane.graphics.info";
  "params": PaneTarget;
}) | ({
  "method": "pane.report_agent";
  "params": PaneReportAgentParams;
}) | ({
  "method": "pane.report_agent_session";
  "params": PaneReportAgentSessionParams;
}) | ({
  "method": "pane.report_metadata";
  "params": PaneReportMetadataParams;
}) | ({
  "method": "pane.clear_agent_authority";
  "params": PaneClearAgentAuthorityParams;
}) | ({
  "method": "pane.release_agent";
  "params": PaneReleaseAgentParams;
}) | ({
  "method": "pane.close";
  "params": PaneTarget;
}) | ({
  "method": "popup.close";
  "params": EmptyParams;
}) | ({
  "method": "events.subscribe";
  "params": EventsSubscribeParams;
}) | ({
  "method": "events.wait";
  "params": EventsWaitParams;
}) | ({
  "method": "pane.wait_for_output";
  "params": PaneWaitForOutputParams;
}) | ({
  "method": "integration.list";
  "params": EmptyParams;
}) | ({
  "method": "integration.install";
  "params": IntegrationInstallParams;
}) | ({
  "method": "integration.uninstall";
  "params": IntegrationUninstallParams;
}) | ({
  "method": "plugin.link";
  "params": PluginLinkParams;
}) | ({
  "method": "plugin.list";
  "params": PluginListParams;
}) | ({
  "method": "plugin.unlink";
  "params": PluginUnlinkParams;
}) | ({
  "method": "plugin.enable";
  "params": PluginSetEnabledParams;
}) | ({
  "method": "plugin.disable";
  "params": PluginSetEnabledParams;
}) | ({
  "method": "plugin.action.list";
  "params": PluginActionListParams;
}) | ({
  "method": "plugin.action.invoke";
  "params": PluginActionInvokeParams;
}) | ({
  "method": "plugin.log.list";
  "params": PluginLogListParams;
}) | ({
  "method": "plugin.pane.open";
  "params": PluginPaneOpenParams;
}) | ({
  "method": "plugin.pane.focus";
  "params": PluginPaneFocusParams;
}) | ({
  "method": "plugin.pane.close";
  "params": PluginPaneCloseParams;
}));

export type SubscriptionEventEnvelope = {
  "data": SubscriptionEventData;
  "event": SubscriptionEventKind;
};

export type SuccessResponse = {
  "id": string;
  "result": ResponseResult;
};

export interface MethodParams {
  "ping": PingParams;
  "server.stop": EmptyParams;
  "server.live_handoff": ServerLiveHandoffParams;
  "server.reload_config": EmptyParams;
  "server.agent_manifests": EmptyParams;
  "server.reload_agent_manifests": EmptyParams;
  "notification.show": NotificationShowParams;
  "product_announcement.dismiss": ProductAnnouncementDismissParams;
  "release_notes.dismiss": ReleaseNotesDismissParams;
  "command.invoke": CommandInvokeParams;
  "client.window_title.set": ClientWindowTitleSetParams;
  "client.window_title.clear": EmptyParams;
  "client_shell.surface.set": ClientShellSurfaceSetParams;
  "session.snapshot": EmptyParams;
  "workspace.create": WorkspaceCreateParams;
  "workspace.list": EmptyParams;
  "workspace.get": WorkspaceTarget;
  "workspace.focus": WorkspaceTarget;
  "workspace.rename": WorkspaceRenameParams;
  "workspace.move": WorkspaceMoveParams;
  "workspace.move_block": WorkspaceMoveBlockParams;
  "workspace.report_metadata": WorkspaceReportMetadataParams;
  "workspace.close": WorkspaceCloseParams;
  "worktree.list": WorktreeListParams;
  "worktree.create": WorktreeCreateParams;
  "worktree.open": WorktreeOpenParams;
  "worktree.remove": WorktreeRemoveParams;
  "tab.create": TabCreateParams;
  "tab.list": TabListParams;
  "tab.get": TabTarget;
  "tab.focus": TabTarget;
  "tab.rename": TabRenameParams;
  "tab.move": TabMoveParams;
  "tab.close": TabTarget;
  "agent.list": EmptyParams;
  "agent.get": AgentTarget;
  "agent.read": AgentReadParams;
  "agent.explain": AgentTarget;
  "agent.send_keys": AgentSendKeysParams;
  "agent.rename": AgentRenameParams;
  "agent.view.set": AgentViewSetParams;
  "agent.view.clear": AgentViewClearParams;
  "agent.focus": AgentTarget;
  "agent.start": AgentStartParams;
  "agent.prompt": AgentPromptParams;
  "agent.wait": AgentWaitParams;
  "pane.split": PaneSplitParams;
  "pane.swap": PaneSwapParams;
  "pane.move": PaneMoveParams;
  "pane.zoom": PaneZoomParams;
  "pane.layout": PaneLayoutParams;
  "pane.process_info": PaneProcessInfoParams;
  "layout.export": LayoutExportParams;
  "layout.apply": LayoutApplyParams;
  "layout.set_split_ratio": LayoutSetSplitRatioParams;
  "pane.neighbor": PaneNeighborParams;
  "pane.edges": PaneEdgesParams;
  "pane.focus_direction": PaneFocusDirectionParams;
  "pane.resize": PaneResizeParams;
  "pane.scroll": PaneScrollParams;
  "pane.edit_scrollback": PaneTarget;
  "pane.selection.read": PaneSelectionReadParams;
  "pane.copy_motion": PaneCopyMotionParams;
  "pane.copy_search": PaneCopySearchParams;
  "pane.list": PaneListParams;
  "pane.current": PaneCurrentParams;
  "pane.get": PaneTarget;
  "pane.focus": PaneTarget;
  "pane.input.set": PaneInputSetParams;
  "pane.link.activate": PaneLinkActivateParams;
  "pane.link.resolve": PaneLinkActivateParams;
  "pane.rename": PaneRenameParams;
  "pane.send_text": PaneSendTextParams;
  "pane.send_keys": PaneSendKeysParams;
  "pane.send_input": PaneSendInputParams;
  "pane.read": PaneReadParams;
  "pane.graphics.set": PaneGraphicsSetParams;
  "pane.graphics.clear": PaneGraphicsClearParams;
  "pane.graphics.info": PaneTarget;
  "pane.report_agent": PaneReportAgentParams;
  "pane.report_agent_session": PaneReportAgentSessionParams;
  "pane.report_metadata": PaneReportMetadataParams;
  "pane.clear_agent_authority": PaneClearAgentAuthorityParams;
  "pane.release_agent": PaneReleaseAgentParams;
  "pane.close": PaneTarget;
  "popup.close": EmptyParams;
  "events.subscribe": EventsSubscribeParams;
  "events.wait": EventsWaitParams;
  "pane.wait_for_output": PaneWaitForOutputParams;
  "integration.list": EmptyParams;
  "integration.install": IntegrationInstallParams;
  "integration.uninstall": IntegrationUninstallParams;
  "plugin.link": PluginLinkParams;
  "plugin.list": PluginListParams;
  "plugin.unlink": PluginUnlinkParams;
  "plugin.enable": PluginSetEnabledParams;
  "plugin.disable": PluginSetEnabledParams;
  "plugin.action.list": PluginActionListParams;
  "plugin.action.invoke": PluginActionInvokeParams;
  "plugin.log.list": PluginLogListParams;
  "plugin.pane.open": PluginPaneOpenParams;
  "plugin.pane.focus": PluginPaneFocusParams;
  "plugin.pane.close": PluginPaneCloseParams;

}

export interface MethodResults {
  "ping": Extract<ResponseResult, { type: "pong" }>;
  "server.stop": Extract<ResponseResult, { type: "ok" }>;
  "server.live_handoff": Extract<ResponseResult, { type: "ok" }>;
  "server.reload_config": Extract<ResponseResult, { type: "config_reload" }>;
  "server.agent_manifests": Extract<ResponseResult, { type: "agent_manifest_status" }>;
  "server.reload_agent_manifests": Extract<ResponseResult, { type: "agent_manifest_reload" }>;
  "notification.show": Extract<ResponseResult, { type: "notification_show" }>;
  "product_announcement.dismiss": Extract<ResponseResult, { type: "ok" }>;
  "release_notes.dismiss": Extract<ResponseResult, { type: "ok" }>;
  "command.invoke": Extract<ResponseResult, { type: "ok" }>;
  "client.window_title.set": Extract<ResponseResult, { type: "client_window_title" }>;
  "client.window_title.clear": Extract<ResponseResult, { type: "client_window_title" }>;
  "client_shell.surface.set": Extract<ResponseResult, { type: "client_shell_surface_set" }>;
  "session.snapshot": Extract<ResponseResult, { type: "session_snapshot" }>;
  "workspace.create": Extract<ResponseResult, { type: "workspace_created" }>;
  "workspace.list": Extract<ResponseResult, { type: "workspace_list" }>;
  "workspace.get": Extract<ResponseResult, { type: "workspace_info" }>;
  "workspace.focus": Extract<ResponseResult, { type: "workspace_info" }>;
  "workspace.rename": Extract<ResponseResult, { type: "workspace_info" }>;
  "workspace.move": Extract<ResponseResult, { type: "workspace_list" }>;
  "workspace.move_block": Extract<ResponseResult, { type: "workspace_list" }>;
  "workspace.report_metadata": Extract<ResponseResult, { type: "ok" }>;
  "workspace.close": Extract<ResponseResult, { type: "ok" }>;
  "worktree.list": Extract<ResponseResult, { type: "worktree_list" }>;
  "worktree.create": Extract<ResponseResult, { type: "worktree_created" }>;
  "worktree.open": Extract<ResponseResult, { type: "worktree_opened" }>;
  "worktree.remove": Extract<ResponseResult, { type: "worktree_removed" }>;
  "tab.create": Extract<ResponseResult, { type: "tab_created" }>;
  "tab.list": Extract<ResponseResult, { type: "tab_list" }>;
  "tab.get": Extract<ResponseResult, { type: "tab_info" }>;
  "tab.focus": Extract<ResponseResult, { type: "tab_info" }>;
  "tab.rename": Extract<ResponseResult, { type: "tab_info" }>;
  "tab.move": Extract<ResponseResult, { type: "tab_list" }>;
  "tab.close": Extract<ResponseResult, { type: "ok" }>;
  "agent.list": Extract<ResponseResult, { type: "agent_list" }>;
  "agent.get": Extract<ResponseResult, { type: "agent_info" }>;
  "agent.read": Extract<ResponseResult, { type: "pane_read" }>;
  "agent.explain": Extract<ResponseResult, { type: "agent_explain" }>;
  "agent.send_keys": Extract<ResponseResult, { type: "ok" }>;
  "agent.rename": Extract<ResponseResult, { type: "agent_info" }>;
  "agent.view.set": Extract<ResponseResult, { type: "agent_view" }>;
  "agent.view.clear": Extract<ResponseResult, { type: "agent_view" }>;
  "agent.focus": Extract<ResponseResult, { type: "agent_info" }>;
  "agent.start": Extract<ResponseResult, { type: "agent_started" }>;
  "agent.prompt": Extract<ResponseResult, { type: "agent_prompted" }>;
  "agent.wait": Extract<ResponseResult, { type: "agent_info" }>;
  "pane.split": Extract<ResponseResult, { type: "pane_info" }>;
  "pane.swap": Extract<ResponseResult, { type: "pane_swap" }>;
  "pane.move": Extract<ResponseResult, { type: "pane_move" }>;
  "pane.zoom": Extract<ResponseResult, { type: "pane_zoom" }>;
  "pane.layout": Extract<ResponseResult, { type: "pane_layout" }>;
  "pane.process_info": Extract<ResponseResult, { type: "pane_process_info" }>;
  "layout.export": Extract<ResponseResult, { type: "layout_export" }>;
  "layout.apply": Extract<ResponseResult, { type: "layout_apply" }>;
  "layout.set_split_ratio": Extract<ResponseResult, { type: "layout_split_ratio_set" }>;
  "pane.neighbor": Extract<ResponseResult, { type: "pane_neighbor" }>;
  "pane.edges": Extract<ResponseResult, { type: "pane_edges" }>;
  "pane.focus_direction": Extract<ResponseResult, { type: "pane_focus_direction" }>;
  "pane.resize": Extract<ResponseResult, { type: "pane_resize" }>;
  "pane.scroll": Extract<ResponseResult, { type: "pane_info" }>;
  "pane.edit_scrollback": Extract<ResponseResult, { type: "ok" }>;
  "pane.selection.read": Extract<ResponseResult, { type: "pane_selection" }>;
  "pane.copy_motion": Extract<ResponseResult, { type: "pane_copy_motion" }>;
  "pane.copy_search": Extract<ResponseResult, { type: "pane_copy_search" }>;
  "pane.list": Extract<ResponseResult, { type: "pane_list" }>;
  "pane.current": Extract<ResponseResult, { type: "pane_current" }>;
  "pane.get": Extract<ResponseResult, { type: "pane_info" }>;
  "pane.focus": Extract<ResponseResult, { type: "pane_info" }>;
  "pane.input.set": Extract<ResponseResult, { type: "ok" }>;
  "pane.link.activate": Extract<ResponseResult, { type: "pane_link_activated" }>;
  "pane.link.resolve": Extract<ResponseResult, { type: "pane_link_resolved" }>;
  "pane.rename": Extract<ResponseResult, { type: "pane_info" }>;
  "pane.send_text": Extract<ResponseResult, { type: "ok" }>;
  "pane.send_keys": Extract<ResponseResult, { type: "ok" }>;
  "pane.send_input": Extract<ResponseResult, { type: "ok" }>;
  "pane.read": Extract<ResponseResult, { type: "pane_read" }>;
  "pane.graphics.set": Extract<ResponseResult, { type: "ok" }>;
  "pane.graphics.clear": Extract<ResponseResult, { type: "ok" }>;
  "pane.graphics.info": Extract<ResponseResult, { type: "pane_graphics_info" }>;
  "pane.report_agent": Extract<ResponseResult, { type: "ok" }>;
  "pane.report_agent_session": Extract<ResponseResult, { type: "ok" }>;
  "pane.report_metadata": Extract<ResponseResult, { type: "ok" }>;
  "pane.clear_agent_authority": Extract<ResponseResult, { type: "ok" }>;
  "pane.release_agent": Extract<ResponseResult, { type: "ok" }>;
  "pane.close": Extract<ResponseResult, { type: "ok" }>;
  "popup.close": Extract<ResponseResult, { type: "ok" }>;
  "events.subscribe": Extract<ResponseResult, { type: "subscription_started" }>;
  "events.wait": Extract<ResponseResult, { type: "wait_matched" }>;
  "pane.wait_for_output": Extract<ResponseResult, { type: "output_matched" }>;
  "integration.list": Extract<ResponseResult, { type: "integration_list" }>;
  "integration.install": Extract<ResponseResult, { type: "integration_install" }>;
  "integration.uninstall": Extract<ResponseResult, { type: "integration_uninstall" }>;
  "plugin.link": Extract<ResponseResult, { type: "plugin_linked" }>;
  "plugin.list": Extract<ResponseResult, { type: "plugin_list" }>;
  "plugin.unlink": Extract<ResponseResult, { type: "plugin_unlinked" }>;
  "plugin.enable": Extract<ResponseResult, { type: "plugin_enabled" }>;
  "plugin.disable": Extract<ResponseResult, { type: "plugin_disabled" }>;
  "plugin.action.list": Extract<ResponseResult, { type: "plugin_action_list" }>;
  "plugin.action.invoke": Extract<ResponseResult, { type: "plugin_action_invoked" }>;
  "plugin.log.list": Extract<ResponseResult, { type: "plugin_log_list" }>;
  "plugin.pane.open": Extract<ResponseResult, { type: "plugin_pane_opened" }>;
  "plugin.pane.focus": Extract<ResponseResult, { type: "plugin_pane_focused" }>;
  "plugin.pane.close": Extract<ResponseResult, { type: "plugin_pane_closed" }>;

}

export type Method = keyof MethodParams;

export type Params<M extends Method> = MethodParams[M];

export type Result<M extends Method> = MethodResults[M];

export type HerdrEvent = EventEnvelope | SubscriptionEventEnvelope;

