#!/usr/bin/env bash
# Refresh the vendored statusline installer from upstream (cell-observatory/claude-statusline).
# Prefers a sibling checkout (../claude-statusline); falls back to GitHub raw. Run from repo root.
set -euo pipefail
cd "$(dirname "$0")/.."
DEST="packages/cli/statusline/install-statusline.sh"
SIBLING="../claude-statusline/install-statusline.sh"
URL="https://raw.githubusercontent.com/cell-observatory/claude-statusline/main/install-statusline.sh"

if [ -f "$SIBLING" ]; then
  SRC_DESC="sibling checkout ($(git -C ../claude-statusline rev-parse --short HEAD 2>/dev/null || echo 'unknown rev'))"
  cp "$SIBLING" "$DEST"
else
  SRC_DESC="$URL"
  curl -fsSL "$URL" -o "$DEST"
fi
chmod +x "$DEST"
bash -n "$DEST"
echo "✓ synced $DEST from $SRC_DESC"
echo "  Update the vendored-commit note in packages/cli/statusline/README.md, then commit."
echo
echo "  ! This file carries LOCAL fixes that upstream does not have yet — a sync silently drops them:"
echo "      • the statusLine command is QUOTED (a config dir with a space, i.e. every Windows box"
echo "        with a spaced username, otherwise reaches Claude Code as two arguments)"
echo "      • the jq error names a Windows install route"
echo "      • the statusline-last.json cache carries EXTRA fields the dashboard renders from"
echo "        (branch, thinking, output_style, tok_in/out/cache, dur_ms, five_total, week_total,"
echo "         plus cost_usd and the per-session \`costs\` spend ledger the money gauges sum) —"
echo "        without them the terminal's statusline silently loses half its content"
echo "      • the tokens-per-percent calibration is the MEASURED sample, not a max() ratchet —"
echo "        a one-way max() locked the estimate above the real figure and could never come down"
echo "      • the window scan DEDUPS by message.id (one assistant message is written as several"
echo "        transcript lines — blind summing measured 2.5-3x high) and counts only THIS machine's"
echo "        own turns by per-line cwd home (synced-in transcripts otherwise double-count the"
echo "        account the moment machines are added up); cache v: 3 + state v: 2 stamp the fix,"
echo "        and every reader refuses to SUM a pre-v3 machine's totals"
echo "      • the usage bars are RULES UNDER THE FIGURES, not bracketed block glyphs: used/total and"
echo "        the cache reads print GREY and the share is UNDERLINED in the usage colour (SGR 4 +"
echo "        SGR 58), between two coloured caps \`▏ ▕\` that give the bar a visible extent — the caps"
echo "        are LITERAL glyphs because bash 3.2 (stock macOS) cannot read \$\'\\u258f\'"
echo "        — upstream still draws \`label [████░░░░] pct% ~used/total\`, which is ~30% wider and wraps"
echo "        on a narrow pane; packages/tui/src/statusline.ts is the byte-for-byte port"
echo "      • EVERY BAR IS ONE LENGTH: a two-pass build (\`defer\`, then \`bw\`) measures the widest"
echo "        figures in the render and CENTRES the figures in it, the ctx gauge on line 2 included"
echo "        — which is why line 2 prints at the END, behind an EXIT trap that still emits a head if"
echo "        the window scan is killed. Dropping the trap loses the whole head on a slow render;"
echo "        dropping the two passes brings back the ragged row. The same pass sets \`labw\`, which"
echo "        pads \`ctx\` and the first window label so their two bars start in one column"
echo "      • the rule runs CAP TO CAP, CAPS INCLUDED in the underlined runs (▏ and ▕ draw at the"
echo "        EDGE of their cell, so an un-underlined cap leaves a visible gap at each end): the"
echo "        usage colour up to the share, \$GY (256-colour grey) past it — and the figures it runs"
echo "        under take the same colours, because an underline has no colour of its own. Do NOT"
echo "        re-add SGR 58: it was tried twice and never reached a real screen, leaving a grey rule."
echo "        \$GY is NOT the DIM attribute, which would dim the rule with it. Centring the figures"
echo "        only works because the rule is continuous — an aligned fill marked blank padding"
echo "      • NO \`|\` divider between the gauges; they are separated by two spaces"
echo "      • the rows WRAP at \$COLUMNS instead of being truncated: \`emit\` packs segments into as"
echo "        few rows as fit, splitting an over-wide one at a secondary separator first. Claude"
echo "        Code exports COLUMNS; \`tput cols\` reads nothing from inside a status line. The money"
echo "        is its OWN segment for the same reason — riding on mo made it too wide to wrap"
echo "      • the LAYOUT: session title closes line 1 (no folder-name fallback — it would print the"
echo "        path twice), ctx opens line 2, line 3 is the quota windows alone"
echo "      • the TITLE ORDER is OAK's: a rename (custom-title, or a session_name that is not the"
echo "        ai-title), then the Remote Control title OAK cached from claude.ai for the transcript's"
echo "        bridge-session id (jq on <store>/remote-cache/session-titles.json, never the network;"
echo "        prefs remoteTitles:false hides it), then session_name / the ai-title"
echo "      • every window prints used/total + cached UNCONDITIONALLY: a window the account puts at"
echo "        0% reads \`~0/59.5M\`, never a blank. est and tot are projections from the same"
echo "        tokens-per-percent, so the pair restates the percentage exactly. Do NOT substitute a"
echo "        MEASURED numerator when the projection is zero (tried 2026-09-15, reverted the same"
echo "        day): measured-over-projected printed ~4M/59.5M — 6.7% — beside a 0% bar"
echo "      • herdr's TAB FOLLOWS THE TITLE: in a herdr pane (HERDR_PANE_ID), a title or pane that differs"
echo "        from the one recorded in <config>/statusline-tab-titles/<session> starts"
echo "        \`oak __tab-sync <session>\` in the background, once per change; the record is written under"
echo "        \`umask 077\`, after \`chmod 700\` on its directory and \`chmod 600\` on its file (a 0700 directory"
echo "        of 0600 files, also where an earlier line left them 0755/0644: a title is conversation content)"
echo "      • the foreign-statusLine guard: the scalar-tolerant jq read (a plain-string statusLine"
echo "        used to kill the script with a silent exit 5), the REFUSED message, and --force + .bak"
echo "      • WINDOWS: \`emit\` prints rows with %s, not %b (a Windows path's \`\\c\` stopped the output"
echo "        and row 1 swallowed row 2), and under Git Bash or Cygwin a native jq.exe / python.exe"
echo "        output loses its CR (every value read from it kept the \\r)"
echo "    \`npm test\` fails if either is missing. Re-apply them, or land them upstream first."
